name: Build and Publish Chrome Extension

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Package extension
        run: |
          mkdir -p dist
          zip -r dist/extension.zip dist

      - name: Publish to Chrome Web Store
        uses: w9jds/publish-extensions@v2
        with:
          extension-id: ${{ secrets.CHROME_EXTENSION_ID }}
          client-id: ${{ secrets.CHROME_EXTENSION_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_EXTENSION_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_EXTENSION_REFRESH_TOKEN }}
          asset: dist/extension.zip
          publish: true
